export const PLAYLIST_DATA = [
  { name: "Blinding Lights", artists: ["The Weeknd"], isDownloaded: false },
  { name: "Save Your Tears", artists: ["The Weeknd"], isDownloaded: true },
  { name: "Positions", artists: ["Ariana Grande"], isDownloaded: false },
  { name: "7 Rings", artists: ["Ariana Grande"], isDownloaded: false },
  { name: "Anti-Hero", artists: ["Taylor Swift"], isDownloaded: true },
  { name: "Shake It Off", artists: ["Taylor Swift"], isDownloaded: false },
  {
    name: "We Don't Talk Anymore",
    artists: ["Charlie Puth", "Selena Gomez"],
    isDownloaded: false,
  },
  { name: "Attention", artists: ["Charlie Puth"], isDownloaded: true },
  {
    name: "Stay",
    artists: ["The Kid LAROI", "Justin Bieber"],
    isDownloaded: false,
  },
  { name: "Peaches", artists: ["Justin Bieber"], isDownloaded: false },
  { name: "As It Was", artists: ["Harry Styles"], isDownloaded: false },
  { name: "Watermelon Sugar", artists: ["Harry Styles"], isDownloaded: true },
  { name: "Flowers", artists: ["Miley Cyrus"], isDownloaded: false },
  { name: "Midnight Sky", artists: ["Miley Cyrus"], isDownloaded: false },
  { name: "Happier Than Ever", artists: ["Billie Eilish"], isDownloaded: true },
  { name: "Bad Guy", artists: ["Billie Eilish"], isDownloaded: false },
  { name: "Levitating", artists: ["Dua Lipa"], isDownloaded: false },
  { name: "Don't Start Now", artists: ["Dua Lipa"], isDownloaded: false },
  { name: "Drivers License", artists: ["Olivia Rodrigo"], isDownloaded: true },
  { name: "Good 4 U", artists: ["Olivia Rodrigo"], isDownloaded: false },
  {
    name: "Someone You Loved",
    artists: ["Lewis Capaldi"],
    isDownloaded: false,
  },
  { name: "Before You Go", artists: ["Lewis Capaldi"], isDownloaded: false },
  { name: "Perfect", artists: ["Ed Sheeran"], isDownloaded: true },
  { name: "Shape of You", artists: ["Ed Sheeran"], isDownloaded: false },
  {
    name: "Señorita",
    artists: ["Shawn Mendes", "Camila Cabello"],
    isDownloaded: false,
  },
  { name: "Stitches", artists: ["Shawn Mendes"], isDownloaded: true },
  { name: "Havana", artists: ["Camila Cabello"], isDownloaded: false },
  {
    name: "Never Be the Same",
    artists: ["Camila Cabello"],
    isDownloaded: false,
  },
  {
    name: "Sunflower",
    artists: ["Post Malone", "Swae Lee"],
    isDownloaded: true,
  },
  { name: "Circles", artists: ["Post Malone"], isDownloaded: false },
  {
    name: "Rockstar",
    artists: ["Post Malone", "21 Savage"],
    isDownloaded: false,
  },
  {
    name: "Montero (Call Me By Your Name)",
    artists: ["Lil Nas X"],
    isDownloaded: false,
  },
  {
    name: "Old Town Road",
    artists: ["Lil Nas X", "Billy Ray Cyrus"],
    isDownloaded: true,
  },
  { name: "Heat Waves", artists: ["Glass Animals"], isDownloaded: false },
  { name: "Yellow", artists: ["Coldplay"], isDownloaded: false },
  { name: "Viva La Vida", artists: ["Coldplay"], isDownloaded: false },
  { name: "Bohemian Rhapsody", artists: ["Queen"], isDownloaded: false },
  { name: "Somebody to Love", artists: ["Queen"], isDownloaded: true },
  { name: "Lose Yourself", artists: ["Eminem"], isDownloaded: false },
  {
    name: "Love the Way You Lie",
    artists: ["Eminem", "Rihanna"],
    isDownloaded: false,
  },
  { name: "Umbrella", artists: ["Rihanna"], isDownloaded: true },
  { name: "Diamonds", artists: ["Rihanna"], isDownloaded: false },
  { name: "Rolling in the Deep", artists: ["Adele"], isDownloaded: false },
  { name: "Hello", artists: ["Adele"], isDownloaded: true },
  { name: "Easy on Me", artists: ["Adele"], isDownloaded: false },
  { name: "Believer", artists: ["Imagine Dragons"], isDownloaded: false },
  { name: "Thunder", artists: ["Imagine Dragons"], isDownloaded: true },
  { name: "Radioactive", artists: ["Imagine Dragons"], isDownloaded: false },
  { name: "Memories", artists: ["Maroon 5"], isDownloaded: false },
  { name: "Sugar", artists: ["Maroon 5"], isDownloaded: true },
];
